spring.application.name=pulseras-api

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://vuquangminh12122004:quangminh12122004exe202@exe202.jiekyer.mongodb.net/EXE202

# Disable JPA
spring.jpa.show-sql=false

# Security Configuration
logging.level.org.springframework.security=INFO
spring.security.user.name=admin
spring.security.user.password=12345
